React Bookstore Milestone-2
SafaErden/React-Bookstore pull request #2
Opened 2020-10-12 13:06 UTC by SafaErden

**In this milestone we:**

- Created all the requested directories,
- Implemented App, Bookslist, Book and BooksForm components,
- Defined the Redux actions and reducers,
- Initialized the Redux store

2020-10-12 15:44 UTC, shloch requested changes
## Hello @SafaErden , @taiwocoker 

You guys did a marvelous job...the hard work and greatest part of this milestone is completely accomplished and shows a demonstration of skill.

We just have small touches here and there to round up before you get final thumbs
This should normally not take you much time

Waiting therefore for a final review...see my comments below

### [changes required]
- still have unfinished business to be done in this file (combining all reducers into ONE) --> `src/reducers/index.js` [ see [REQUIREMENTS](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/bookstore/milestone2/ReducxReducers/CombinesAppReducers.png)]

Happy coding

2020-10-12 15:44 UTC, shloch commented on src/components/BooksList.js
> +import { connect } from 'react-redux';
If you read the requirement again, you'll notice that these components
- `BookLists`
- `BookForm`
being "container" components should be in the `src/containers/` folder

This is a minor issue, but please relocate these two files for final thumbs up

2020-10-12 15:44 UTC, shloch commented on src/acitons/index.js
> +  payload: book,
small typo error...... you names folder this component is as `acitons` instead of `actions`

2020-10-13 13:55 UTC, Torres-ssf approved these changes
### Milestone approved :+1: 
Hi there team :hand: 
Great job on this milestone and implementing the requested changes.

Happy Coding :computer: 
**Sergio Torres**

2020-10-13 13:55 UTC, Torres-ssf commented on src/components/App.js
> +      <BooksList key={12345} />
- Why the `key` attribute is being assigned here? Is this necessary :thinking: ?

2020-10-14 09:05 UTC, merged